### PR TITLE
pin libsass to 0.10.0, to unbreak `compress`

### PR DESCRIPTION
**Pull request by jimabramson**
@rlucioni @AlasdairSwan @clintonb @zubair-arbi FYI

### CODE REVIEW

**Comment by clintonb** [comment]
:+1:

**Comment by rlucioni** [comment]
:+1: . I'll pull this change out of https://github.com/edx/programs/pull/96.

**Comment by jimabramson** [comment]
@rlucioni thanks, didn't realize you had done that.

**Comment by rlucioni** [comment]
@jimabramson no worries, it's more appropriate as its own commit.

**Pull request merged**
