### PR TITLE
Squashed migrations

### PR DESCRIPTION
**Pull request by clintonb**
Manually "squashed" migrations by deleting existing migrations and re-running the command to migration generation command. This is only acceptable since we have not yet deployed the application. Also, field with character length of 256 was update to a length of 255.

ECOM-2186

@jimabramson @rlucioni 

FYI @jibsheet we will need to regenerate the base image for devstack and sandboxes.

### CODE REVIEW

**Comment by rlucioni** [comment]
:+1:

**Comment by jimabramson** [comment]
@clintonb looks good.  As long as you're cleaning stuff up - this stuff isn't needed any longer
https://github.com/edx/programs/blob/squash-migrations/programs/apps/programs/migrations/0002_create_groups.py#L18-L27
because we've ditched django model permissions.  We only need to create the groups.  Would you be willing to remove that as well?

**Comment by jimabramson** [comment]
@clintonb also, the 2^n -> 2^n-1 change you made on that course_key field, are there any other fields to which it would make sense to apply that?

**Comment by jimabramson** [comment]
@clintonb ignore me on that last thing about field length, i just found [the SO link you posted](http://stackoverflow.com/questions/1814532/1071-specified-key-was-too-long-max-key-length-is-767-bytes/16820166#16820166) explaining why you did that.

**Comment by jimabramson** [comment]
@clintonb feel free to merge as is, the 0002 migration can be cleaned up in another PR.  :+1: 

@jibsheet this may resolve ECOM-2571

**Comment by clintonb** [comment]
@jimabramson migration updated.

**Comment by clintonb** [comment]
@jimabramson I also update two other charfield limits.

**Comment by jimabramson** [comment]
:+1: :+1:

**Pull request merged**
