### PR TITLE
Add edx-django-release-util

### PR DESCRIPTION
**Pull request by efischer19**
[TE-1500](https://openedx.atlassian.net/browse/TE-1500)

### CODE REVIEW

**Comment by efischer19** [comment]
@rlucioni Can you give this a quick review? It's adding tools that aren't used currently, but could help the platform/deployment team in the future.

**Comment by rlucioni** [comment]
@efischer19 I assume this exposes some management commands?

**Comment by rlucioni** [comment]
I could also just read the ticket...

👍

**Comment by efischer19** [comment]
Correct: https://github.com/edx/edx-django-release-util/tree/master/release_util/management/commands

**Pull request merged**
