### PR TITLE
Upgrade to Django 1.9.4

### PR DESCRIPTION
**Pull request by rlucioni**
For reference, see the Django 1.9 [release notes](https://docs.djangoproject.com/en/1.9/releases/1.9/). @jimabramson, any reason not to make the jump?

### CODE REVIEW

**Comment by jimabramson** [comment]
@rlucioni well, the broken build is one reason :-)

**Comment by rlucioni** [comment]
@jimabramson django-compressor :disappointed:. I want the sexy new admin!

**Comment by rlucioni** [comment]
@jimabramson got the green light!

**Comment by jimabramson** [comment]
:+1: :+1:

**Pull request merged**
