### PR TITLE
Upgrade Django to 1.8.15

### PR DESCRIPTION
**Pull request by rlucioni**
@nedbat

### CODE REVIEW

**Comment by rlucioni** [comment]
jshint failures are a surprise to me, I don't want to make changes apart from the Django upgrade here.

**Comment by nedbat** [comment]
Any clue why jshint is failing? Is it something master has addressed?

**Comment by rlucioni** [comment]
@nedbat that must be it, I merged a PR yesterday that passed all checks. Thoughts on what to do here?

**Comment by nedbat** [comment]
Not sure why it used to pass, that line is clearly too long, but it's gone from master since 111be60c6c5b9ea68b53a3eb9697350dd8664eac.  This is good to merge. :+1:

**Pull request merged**
