### PR TITLE
Unpack media storage settings when applying config overrides

### PR DESCRIPTION
**Pull request by rlucioni**
@e0d @maxrothman @clintonb 

This was removed in https://github.com/edx/programs/commit/ec2a6cd8a01bff561e8d0b61988be68c8ea1d949#diff-2ca989f014687f3223a751f4dbc2756eL34.

### CODE REVIEW

**Comment by clintonb** [comment]
Why/how is `MEDIA_STORAGE_BACKEND` different from `JWT_AUTH`? The idea there is that dictionaries are updated from settings rather than replaced.

**Comment by clintonb** [comment]
Also, is there an acceptance test we can update to confirm this is fixed?

**Comment by rlucioni** [comment]
@clintonb the contents of `MEDIA_STORAGE_BACKEND` need to be unpacked in order to override other settings. See [here](https://github.com/edx/configuration/blob/master/playbooks/roles/programs/defaults/main.yml#L94) for an example of how that dictionary might look. Note how `MEDIA_URL` and `MEDIA_ROOT` are contained in that dictionary.

**Comment by rlucioni** [comment]
@clintonb I'm not aware of existing tests covering the loading/overriding of settings in production environments. If we had such tests, this would likely have been caught. I'd be happy to look into adding them, though I'd prefer to take care of that separately.

**Comment by clintonb** [comment]
Wait...why are we using an unorthodox setting like `MEDIA_STORAGE_BACKEND`? There were no comments on that setting, so I assumed it was another `dict` to be set, similar to `JWT_AUTH`. Can we use the actual settings—`DEFAULT_FILE_STORAGE`, `MEDIA_ROOT`, `MEDIA_URL`—and avoid this confusion in the future?

**Comment by rlucioni** [comment]
@clintonb I remember it being a deliberate choice, though I'm having trouble remembering/finding a record of the justification for it. I remember @maxrothman was pretty opinionated about this approach. @maxrothman any chance you remember the reasoning around this?

**Comment by maxrothman** [comment]
We'd prefer to group all the settings necessary to switch between backends in configuration so they can be swapped easily. `MEDIA_STORAGE_BACKEND` contains all the standard settings, it just wraps them so it's easy to tell which ones go together.

**Comment by clintonb** [comment]
How often do we switch backends? This is a solution to a non-existent problem, and it's too clever for its own good, hence our having this conversation now.

**Comment by e0d** [comment]
I'm :+1: to release this and debate the best factoring later.

**Comment by clintonb** [comment]
👍 (pending):

1. Remove `MEDIA_STORAGE_BACKEND ` from `DICT_UPDATE_KEYS`
2. Create a ticket to replace `MEDIA_STORAGE_BACKEND` with the individual settings.

**Comment by maxrothman** [comment]
👍 for this change

@clintonb we change backends constantly: we use local file storage for devstacks/sandboxes and s3 for prod/stage/loadtest. Members of the community use openstack, local file storage, azure, and lots of other solutions.

**Comment by clintonb** [comment]
@maxrothman the same case could be made for practically every setting in edx/configuration. There isn't a good case for treating these settings any differently than others.

**Comment by maxrothman** [comment]
@clintonb I've already explained why this is a special case. Most other settings don't come in big groups and aren't changed in a decent chunk of deployments. I understand that's it's ugly to have a special case here, but configuration is the interface most open-source users use to customize their deployment. That interface should make it easy to do the most common things people want to do, one of which is switch storage backends. Switching storage backends is otherwise a complex and fragile process.

**Pull request merged**
