### PR TITLE
Revert "Upgrade to Django 1.9.4"

### PR DESCRIPTION
**Pull request by schenedx**
This reverts commit 59764104a6ae8bf1d6877aed825696f89c7394d9.

### CODE REVIEW

**Comment by jimabramson** [comment]
👍

**Comment by nedbat** [comment]
Just noticed this PR.  There is a long-standing open issue about whether we should aim for LTS releases where we can, or whether we should upgrade eagerly.  Somehow we should get this raised.

**Comment by jimabramson** [comment]
@nedbat excellent point, thanks for bringing that up.

**Comment by jimabramson** [comment]
follow up is in ARCH-39

**Pull request merged**
