### PR TITLE
Add codecov.yml

### PR DESCRIPTION
**Pull request by rlucioni**
Codecov now uses a YAML settings file. The settings here mirror our pre-YAML configuration.

@schenedx @jimabramson

### CODE REVIEW

**Comment by schenedx** [comment]
👍

**Comment by jimabramson** [comment]
LGTM, but doesn't the earlier configuration get removed?

**Comment by rlucioni** [comment]
@jimabramson our old configuration for this repo (and every repo using Codecov) is gone and has been reset to Codecov's defaults. Adding this YAML file appears to be the only way to restore our old config.

**Comment by jimabramson** [comment]
@rlucioni  understood thanks.   👍

**Pull request merged**
