### PR TITLE
Add interface for program completion endpoint

### PR DESCRIPTION
**Pull request by rlucioni**
The endpoint currently returns all program IDs, but will be refined soon. ECOM-3352.

@jimabramson

### CODE REVIEW

**Comment by jimabramson** [comment]
@rlucioni looks good, although we need to update the request payload as mentioned in https://github.com/edx/edx-platform/pull/11318/files#r50644758

Curious why you chose PUT over POST for this.

**Comment by rlucioni** [comment]
@jimabramson I went with PUT because it's meant to be idempotent, unlike POST. Requests to this endpoint should be idempotent.

**Comment by rlucioni** [comment]
@jimabramson request payload updated to reflect changes in https://github.com/edx/edx-platform/pull/11318/.

**Comment by rlucioni** [comment]
@jimabramson updated to use POST in light of our discussion.

**Comment by jimabramson** [comment]
:+1: once tests pass.   Note to selves: update API documentation.

**Comment by rlucioni** [comment]
@jimabramson when you say API documentation, are you referring to the viewset docstring?

**Comment by jimabramson** [comment]
@rlucioni yeah, and whatever else exists; i notice there's no doc updates introduced in this PR but I consider that OK as the endpoint isn't actually implemented yet

**Pull request merged**
