### PR TITLE
Remove django-waffle (unused)

### PR DESCRIPTION
**Pull request by rlucioni**
I was going to upgrade to 0.11.1 but then realized this project doesn't actually use Waffle.

@edx/ecommerce

### CODE REVIEW

**Comment by clintonb** [comment]
👍 

Note that the tables will remain in the database, which isn't necessarily a bad thing.

**Comment by rlucioni** [comment]
@clintonb do you know if that will cause problems should we chose to re-introduce the dependency at a later date?

**Comment by clintonb** [comment]
It shouldn't. Those migrations will be skipped.

**Comment by schenedx** [comment]
👍

**Pull request merged**
